# Generated by Django 2.0 on 2020-06-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='etf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('etf50', models.FloatField(null=True)),
                ('etf300', models.FloatField(null=True)),
                ('es', models.FloatField(null=True)),
                ('hs', models.FloatField(null=True)),
                ('sz', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'etf',
            },
        ),
        migrations.CreateModel(
            name='iv_mean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('iv_50', models.FloatField()),
                ('iv_300', models.FloatField()),
            ],
            options={
                'db_table': 'iv_mean',
            },
        ),
        migrations.CreateModel(
            name='options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('price', models.FloatField()),
                ('eprice', models.FloatField()),
                ('eday', models.DateField()),
                ('day', models.DateField()),
                ('iv', models.FloatField()),
            ],
            options={
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
            ],
            options={
                'db_table': 'volume',
            },
        ),
    ]
