# Generated by Django 2.0 on 2020-05-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('eprice', models.FloatField()),
                ('time', models.DateTimeField()),
                ('iv', models.FloatField()),
            ],
        ),
    ]
