# Generated by Django 2.0 on 2020-05-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='iv_mean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('iv', models.FloatField()),
                ('target', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='name_op',
            field=models.CharField(default='', max_length=20),
        ),
    ]
