# Generated by Django 2.0 on 2020-05-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_view', '0003_auto_20200523_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iv_mean',
            name='time',
            field=models.TimeField(),
        ),
    ]
