# Generated by Django 2.0 on 2020-05-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_view', '0004_auto_20200523_0313'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='iv_mean',
            table='iv_mean',
        ),
    ]
