# Generated by Django 2.0 on 2020-05-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_view', '0005_auto_20200523_0554'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='option',
            table='option',
        ),
    ]
