# Generated by Django 2.0 on 2020-05-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_view', '0006_auto_20200523_0555'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='iv_mean',
            table=None,
        ),
        migrations.AlterModelTable(
            name='option',
            table=None,
        ),
    ]
