# Generated by Django 2.0 on 2020-05-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_view', '0007_auto_20200523_0643'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='iv_mean',
            table='iv_mean',
        ),
        migrations.AlterModelTable(
            name='option',
            table='option',
        ),
    ]
