# Generated by Django 2.0 on 2020-05-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_view', '0008_auto_20200523_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
            ],
            options={
                'db_table': 'volume',
            },
        ),
    ]
