# Generated by Django 2.0 on 2020-05-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_view', '0009_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('price', models.FloatField()),
                ('eprice', models.FloatField()),
                ('eday', models.DateField()),
                ('day', models.DateField()),
                ('iv', models.FloatField()),
            ],
            options={
                'db_table': 'options',
            },
        ),
        migrations.DeleteModel(
            name='option',
        ),
    ]
