# Generated by Django 2.0 on 2020-05-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_view', '0010_auto_20200526_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='etf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('etf_50', models.FloatField()),
                ('etf_300', models.FloatField()),
                ('es', models.FloatField()),
                ('etf_hs', models.FloatField()),
                ('etf_sz', models.FloatField()),
            ],
            options={
                'db_table': 'etf',
            },
        ),
    ]
