# Generated by Django 3.0.3 on 2020-05-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_view', '0011_etf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='es',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='etf',
            name='etf_300',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='etf',
            name='etf_50',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='etf',
            name='etf_hs',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='etf',
            name='etf_sz',
            field=models.FloatField(null=True),
        ),
    ]
